name: Build

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      file_name:
        description: "input file name"
        required: true
        default: "b.cpp"
        type: choice
        options:
          - a.cpp
          - b.cpp
          - c.cpp
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04]

    steps:
      - name: Print OS
        run: echo "Running on ${{ matrix.os }}"
        
  cpp-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile 
      run: g++ -std=c++17 ${{ inputs.file_name }} -o a

    - name: Run executable
      run: ./a  
